Revert tests to sshd-core from 0.8.0 to 0.7.0 because of some MINA dependency issue: java.lang.NoSuchMethodError: org.apache.mina.core.service.IoAcceptor.bind([Ljava/net/SocketAddress;)V         at org.apache.sshd.SshServer.start(SshServer.java:353)         at org.apache.commons.vfs2.provider.sftp.test.SftpProviderTestCase.setUpClass(SftpProviderTestCase.java:253)
git-svn-id: https://svn.apache.org/repos/asf/commons/proper/vfs@1395117 13f79535-47bb-0310-9956-ffa450edef68